_target_: src.llms.gemini.Gemini_Agent
api_key: "AIzaSyD9ncbi4jtMT1iS0t0yv8nRg9ImUMwH9Bo" #benrygta@gmail.com 
config:
  llm_configs:
    config_1:
      model_name: "gemini-2.0-flash"
      generation_config:
        temperature: 0.2
        top_p: 0.5
        top_k: 10

    config_2:
        model_name: "gemini-2.0-flash"
        generation_config:
          temperature: 1.2
          top_p: 0.95
          top_k: 40

    config_3:
        model_name: "gemini-2.0-flash"
        generation_config:
          temperature: 0.6
          top_p: 0.5
          top_k: 40