_target_: src.classifier.softmax.Softmax_Classifier

config:
  name: "softmax_classifier"

  # for lstm
  bidirectional: True
  lstm_layers: 1
  embedding_dim: 128

  # for softmax
  latent_dim: 32
  batch_size: 32
  lr: 0.001 # best for adam
  epochs: 200
  num_hidden_layers: 2
  num_hidden_units: 30
  dropout_prob: 0.7